FROM pytorch/pytorch:2.7.1-cuda12.6-cudnn9-runtime

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt

# PyTorch ist im Basisimage schon vorhanden.
# torch deshalb nicht noch einmal aus requirements installieren.
RUN grep -vE '^torch([<>=].*)?$' /app/requirements.txt > /app/requirements.no_torch.txt && \
    python -m pip install --upgrade pip "setuptools<81" wheel && \
    python -m pip install -r /app/requirements.no_torch.txt

COPY src /app/src
COPY scripts /app/scripts
COPY configs /app/configs
COPY data/cafa-5-protein-function-prediction/Train/train_terms.tsv /app/data/cafa-5-protein-function-prediction/Train/train_terms.tsv

ENTRYPOINT ["python"]
